### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by antonkomarev** [MCStreetguy/ComposerParser#2]
@MCStreetguy could you publish stable release, please? It's very risky to rely on `dev-master` on production.

**Comment by MCStreetguy** [comment]
I originally wanted to test the project extensively before I released a stable version, but the package has been functional for a very long time now without any changes, so I think I can definitely do that.

**Comment by MCStreetguy** [comment]
v1.0 is on it's way and should be available on Packagist in a moment.
