### ISSUE TITLE
Add packagist.org to Repositories

### ISSUE THREAD

**Issue by antonkomarev** [MCStreetguy/ComposerParser#4]
Accordingly to the specification - there is a way to [disable packagist.org](https://getcomposer.org/doc/05-repositories.md#disabling-packagist-org). 

But if you add it to composer.json - parser will return this value:
```json
{"type":"","url":"","options":[],"package":null}
```

Maybe it will be better to have by default packagist repository in list:
```json
"packagist.org": {
  "type": "composer",
  "url": "https?://repo.packagist.org",
  "allow_ssl_downgrade": true
},
```

And remove it if `"packagist.org": false` is in place?

Or just not to add this object to the parsed repositories list, but then we need to denote that packagist is disabled somehow.

**Comment by antonkomarev** [comment]
One more note - packagist.org could be disabled via global config:
```sh
$ composer config -g repo.packagist false
```

**Comment by MCStreetguy** [comment]
I think this could be implemented easily, even with taking the global scope into consideration.
As the global config-file location is somewhat static, we could retrieve it during runtime without much effort. ([see here for reference](https://getcomposer.org/doc/03-cli.md#composer-home-config-json))
Then we could merge the data before passing it on to the ComposerJson and Lockfile constructors.
That way the purpose of both classes does not get obfuscated, as these should solely represent the passed data, without any unrelated magic funtionality.

In this case we could also stick to your first suggestion, add packagist.org by default to the repositories list and remove it if it's set to false.
As the data would be merged before arriving at the constructor, the class itself would not have to deal with from where the directive arises.

I don't know if I can look into it soon, as I got much work to do currently, but I'll try to fix this later on this week.

**Comment by antonkomarev** [comment]
Also there is `"allow_ssl_downgrade": true` settings inside of the repository. It's not documented, but exists in [sources](https://github.com/composer/composer/blob/0fe200d6d950b0774688713be3153bb410eb70b8/src/Composer/Repository/ComposerRepository.php#L87-L89).

**Comment by MCStreetguy** [comment]
Good tip, thanks! Then I add this setting directly to the corresponding class when I make the adjustments.

**Comment by antonkomarev** [comment]
If I understand it right - all the repositories has numeric keys, but `packagist.org` has string key and should be listed at the end of the array, because ordering is important for the priority resolving.

**Comment by MCStreetguy** [comment]
@antonkomarev I changed several parts of the library to what we discussed before.
From my side this looks fine, but I don't got that much time to test currently.
Would you be so kind and check if the adapted code works for your described situation?
You can find the proposed changes in the `master` branch.

**Comment by antonkomarev** [comment]
It's working, thanks!
